# Generated by Django 5.2 on 2025-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('RP', 'Rap'), ('R&B', 'REGGAE'), ('HP', 'Hip-Hop')], default='--'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('ML', 'MALE'), ('FM', 'FEMALE')], default='--'),
        ),
    ]
