# Generated by Django 5.2 on 2025-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0002_artist_genre_alter_artist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('RP', 'Rap'), ('R&B', 'REGGAE'), ('HP', 'Hip-Hop'), ('SD', 'SAD')], default='--'),
        ),
    ]
