# Generated by Django 5.2 on 2025-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0003_alter_artist_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('RP', 'Rap'), ('R&B', 'REGGAE'), ('HP', 'Hip-Hop'), ('SD', 'SAD')], max_length=50)),
            ],
        ),
    ]
