# Generated by Django 5.2 on 2025-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0004_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('RP', 'Rap'), ('R&B', 'REGGAE'), ('HP', 'Hip-Hop'), ('SD', 'SAD')], default='--', max_length=50),
        ),
    ]
